trigger:
- '*'
  
schedules:
- cron: 0 3 * * Sun
    displayName: Schedule weekly builds
    branches:
    include: ['master']
    always: true
    
extends:
  template: CI.yml
  variables:
  - group: BusinessCentral16
  - group: InsiderBuild


    