trigger:
- '*'
    
schedules:
- cron: 0 3 * * Sun
    displayName: Schedule weekly builds
    branches:
    include: ['master']
    always: true

variables:
- group: BusinessCentral16
- group: InsiderBuild
- name: version
    value: "nextmajor"
    
extends:
    template: CI.yml
    